### ISSUE TITLE
Image upload tab issue

### ISSUE THREAD

**Issue by Spasmaticus** [imprex92/dark-traveling-marshmallow#143]
When tabbing through the guide the slides/windows act odd and the slides change position and size sometimes. Plus the order of tabbing seems to be a bit random. In my case it ended up switching between slide 2, 3 and a mix of them.
Recreate by tabbing on the last page repeatedly. (Sped up with 1.4x)

https://github.com/imprex92/dark-traveling-marshmallow/assets/136021321/09bb9174-6cbf-4d66-ab96-301bc2690059

**Comment by imprex92** [comment]
Will be fixed in the new form version #160
